version: '3'

volumes: 
  docker-volume:

services: 
  web:
    build: 
      context: ./.docker/web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    depends_on: 
      - app
    volumes: 
      - ./.docker/web/default.my.conf:/etc/apache2/site-enabled/000-default.conf
      - .:/var/www/html

  app:
    build: 
      context: ./.docker/php
      dockerfile: Dockerfile
  
    volumes: 
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html

  db:
    build: 
      context: ./.docker/db
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}

    volumes: 
      - docker-volume:/var/lib/mysql
